const colors = {
  light: {
    text: "#FFFFFF",
    tint: "#7B2FF7",
    background: "#0A0A1A",
    foreground: "#FFFFFF",
    card: "#141428",
    cardForeground: "#FFFFFF",
    primary: "#7B2FF7",
    primaryForeground: "#FFFFFF",
    secondary: "#1E1E38",
    secondaryForeground: "#CCCCEE",
    muted: "#1A1A32",
    mutedForeground: "#8888AA",
    accent: "#F5A623",
    accentForeground: "#0A0A1A",
    destructive: "#FF4D6A",
    destructiveForeground: "#FFFFFF",
    border: "#2A2A44",
    input: "#1E1E38",
    gold: "#F5A623",
    pink: "#FF6B9D",
    teal: "#00D4A0",
    purple: "#7B2FF7",
    purpleLight: "#9B5FFF",
    purpleDark: "#5B1BBF",
    seatBg: "#1E1E38",
    hostRing: "#F5A623",
    speakerRing: "#7B2FF7",
  },
  radius: 12,
};

export default colors;
